# Generated by Django 4.2.5 on 2023-09-19 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=30, null=True)),
                ('amount', models.IntegerField()),
                ('payment_type', models.CharField(choices=[('ussd', 'ussd'), ('bank-card', 'bank-card'), ('bank-transfer', 'bank-transfer')], max_length=50, null=True)),
                ('payment_plan', models.CharField(choices=[('Monthly', 'Monthly'), ('6-month', '6-month'), ('Yearly', 'Yearly')], max_length=50, null=True)),
                ('date', models.DateTimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
