# Generated by Django 4.2.5 on 2023-09-19 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=50)),
                ('order_la', models.CharField(choices=[('agege', 'Agege'), ('ajeromi-ifelodun', 'Ajeromi-Ifelodun'), ('alimosho', 'Alimosho'), ('amuwo-odofin', 'Amuwo-Odofin'), ('apapa', 'Apapa'), ('badagry', 'Badagry'), ('epe', 'Epe'), ('Eti-Osa', 'Eti-Osa'), ('ibeju-lekki', 'Ibeju-Lekki'), ('ifako-ijaiye', 'Ifako-Ijaiye'), ('ikeja', 'Ikeja'), ('ikorodu', 'Ikorodu'), ('kosofe', 'Kosofe'), ('lagos-island', 'Lagos Island'), ('lagos-mainland', 'Lagos Mainland'), ('mushin', 'Mushin'), ('ojo', 'Ojo'), ('oshodi-isolo', 'Oshodi-Isolo'), ('somolu', 'Somolu'), ('surulere', 'Surulere')], max_length=50, null=True)),
                ('address', models.CharField(max_length=50)),
                ('order_quantity', models.IntegerField()),
                ('order_size', models.IntegerField(null=True)),
                ('order_price', models.IntegerField(null=True)),
                ('recipient_number', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(default='uncomplete', max_length=50)),
                ('rider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='order_complete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_complete_image', models.ImageField(upload_to='order_complete')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
